apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nodejs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-nodejs
    spec:
      containers:
      - name: demo-node
        image: emoburneraccount/ci-testing:1.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
