###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build nodejs
      run: |
        CONTAINER_IMAGE_TAG=1.0
        docker build . -t demoburneraccount/ci-testing:$CONTAINER_IMAGE_TAG
    - name: docker push
      run: |
        docker push demoburneraccount/ci-testing:$CONTAINER_IMAGE_TAG
